inherit_from: .rubocop_todo.yml

AllCops:
    Exclude:
        - 'extensions/**/*'
        - 'skins/**/*'
        - 'tests/frontend/node_modules/**/*'
        - 'vendor/**/*'

Metrics/LineLength:
  Max: 100
